### ISSUE TITLE
Try to track user activity in google spreadsheets

### ISSUE THREAD

**Issue by zarvox** [deathandmayhem/jolly-roger#107]
Today, Jolly Roger only knows who's working on a puzzle by virtue of who has the puzzle page open, but that's pretty coarse - people tend to open lots of puzzle pages when they're skimming through, and leave them open even when they're not actively working on the puzzle.

It'd be nice if we could get an event changestream from Google Sheets to tell when someone was actively editing the sheet, since that's a much stronger indicator of activity.

**Comment by ebroder** [comment]
It looks like we might be able to get this information using Google Apps Script's triggers functionality, which comes in two forms: [simple](https://developers.google.com/apps-script/guides/triggers) and [installable](https://developers.google.com/apps-script/guides/triggers/installable). It's not entirely clear to me whether we need installable or could get away with simple.
