### ISSUE TITLE
Reevaluate customization of markdown formatting

### ISSUE THREAD

**Issue by ebroder** [deathandmayhem/jolly-roger#1162]
We're using a somewhat old version of `marked` these days. It's something of a broken window, as there's an outstanding regex DoS vulnerability, but I haven't dealt with it, mostly because I haven't wanted to fight with our customization of its formatting. Before fighting with our customization, I think it's worth having a discussion about whether we actually care.

We've historically made modifications to how `marked` formats Markdown to make it consistent with how Slack formatted text - Slack uses `*` for bold and `_` for Italics, instead of Markdown standard (`*` or `_` for italics and `**` or `__` for bold). I think a decent number of chat apps (e.g. Skype) uses the same rough formatting rules as Slack, but Discord and Github both use standard markdown. This means that when we pipe chat messages into Discord, they get formatted differently.

My intuition is that we should just switch to default behavior and let people adjust. It'll mis-format old messages but not dramatically, and people may be slightly confused, but realistically the difference between bold and italic is mostly pretty slight.

**Comment by zarvox** [comment]
Seems reasonable to me.  

If we're open to larger scope, we might also think about reimagining the input box into something akin to how Discord renders some of the formatting in the edit box while you're still editing.

Another thing that might be nice for folks who are less familiar with the formatting options available would be adding a toggleable popover explaining supported formatting.
