### ISSUE TITLE
Tooltips stacked under toasts

### ISSUE THREAD

**Issue by ebroder** [deathandmayhem/jolly-roger#1228]
Now that we're using the new React toast component (#1219), it looks like tooltips are rendered at a lower z-index than the toasts themselves:

<img width="434" alt="Screenshot 2022-12-22 at 9 47 07 AM" src="https://user-images.githubusercontent.com/28167/209195240-7318ef47-dc67-4438-b2a5-c7750e9afbd6.png">

It's worth noting that Bootstrap has variables to control these, implying that this behavior is intentional: https://github.com/twbs/bootstrap/blob/41f62c5a11d98d49646296f996fa844d05f9514d/scss/_variables.scss#L1087-L1113

We may be able to just override those (even though it says not to), similar to other overrides in `_theme.scss`.

**Comment by zarvox** [comment]
FWIW, I am unable to reproduce this issue locally at HEAD.  I did, however, run into it during development if I removed the line at https://github.com/deathandmayhem/jolly-roger/blob/18609e4a627f15766e6e24f4b7b365c9462fd887/imports/client/components/NotificationCenter.tsx#L376 though.

Are you seeing this behavior at HEAD?

**Comment by ebroder** [comment]
Fascinating. No, I don't see it on head. I must not have been caught up.
