### ISSUE TITLE
Consider making it easier to return to puzzles you were working on previously

### ISSUE THREAD

**Issue by zarvox** [deathandmayhem/jolly-roger#1368]
From a user in Discord post-hunt:

> This is one of those "maybe it already exists" things, but is there any kind of bookmarking/favoriting/recently-opened functionality in JR? Whenever I go to sleep, I usually just leave the tabs of the puzzles I was looking open to see how things are going, but this year I had a couple of times where my browser crashed or I had to restart my computer, and I ended up digging the puzzles out of my browser history to see if they'd been solved or still needed eyes because I couldn't remember their names. There are ways I could get around this via external bookmarking (browser bookmarking, dumping all of the puzzles I'm interested in into a markdown file, whatever) but within JR would be pretty cool.

Maybe this winds up being a separate sort order option, or a "my recent activity" view option or something?  I could believe this would work either with the server-side activity tracking data from our various activity sources, or possibly with just client-side localStorage records that we write (which would probably be able to easily consider navigations but less likely document or call activity).

**Comment by ebroder** [comment]
It feels like it would be challenging to make a "most recent activity" sort useful across the different ways people use Jolly Roger, especially for the type of person who opens a lot of pages briefly. I feel somewhat more inclined to experiment with bookmarking, which potentially could also let us do things like push a notification to you when a bookmarked puzzle is solved

**Comment by Apophenia** [comment]
I think bookmarking would be a totally sufficient way to solve this problem for me, imo, especially since I do open lots of puzzles and think "hmm, not for me!"

I envisioned this as being some sort of optional/toggleable grouping that might show up at the top of the main puzzle list page, something like this:
![image](https://user-images.githubusercontent.com/2042238/212784652-d4e4b457-6c93-4e65-823e-9f8f76a1a990.png)
but I think this is just one of many potential ways to implement this.

**Comment by Apophenia** [comment]
I think there are a number of ways this could work and still be useful to me -- my main use case is wanting to restart my browser, machine, or switch to/from my iPad, and allowing favorites would totally solve that problem. Pushing a notification when a bookmarked puzzle is solved would be great, too.

Here's one way I can imagine it looking:

![image](https://user-images.githubusercontent.com/2042238/212785848-8d077ba8-ce9f-40ef-8e9a-402f68793143.png)

**Comment by flipdog** [comment]
This feels like the kind of thing where a "less is more" approach would make the most sense. I think a simple "puzzle bookmarking" scheme, where you easily 1-click follow a puzzle (which many apps like slack already have an intuitive UI for) and just as easily "unfollow" after it's been solved or you've lost interest would serve most of these purposes.

I also really love the idea of getting "ding-word" notified when something you follow is solved.
