### ISSUE TITLE
Client-side exceptions due to deleted puzzles

### ISSUE THREAD

**Issue by ebroder** [deathandmayhem/jolly-roger#1371]
If a puzzle that received guesses is deleted, the GuessQueuePage crashes (because it loads puzzles, but not puzzles-allowing-deleted):

```
TypeError Cannot read properties of undefined (reading 'url') 
    imports/model-helpers.ts:39:14 s
    imports/client/components/GuessQueuePage.tsx:234:19 
```

We also saw an error in NotificationCenter that seems related:

```
TypeError undefined is not an object (evaluating 'n.hunt') 
    imports/client/components/NotificationCenter.tsx:161:38 
```

**Comment by ebroder** [comment]
This issue has been linked to an error in Bugsnag
[**TypeError** in **/hunts/m8meaNgtfrKfkiapd/guesses**](https://app.bugsnag.com/death-and-mayhem/jolly-roger/errors/63c392c52715fa0009f9269e?event_id=63c3939a00aaa3d06ff80000&i=gh&m=li)

**Comment by ebroder** [comment]
I suspect there may be similar issues in the NotificationCenter.

I'm going to group this under a single ticket, since they should be relatively easy to fix at the same time (and I don't want to spam the issue tracker with deleted puzzle issues)

**Comment by ebroder** [comment]
This issue has been linked to an error in Bugsnag
[**TypeError** in **/hunts/m8meaNgtfrKfkiapd/puzzles/ENQkY3u8LPHGasBmN**](https://app.bugsnag.com/death-and-mayhem/jolly-roger/errors/63c4220ea6d0b30008b59ad2?event_id=63c4220e00aad08662e70000&i=gh&m=li)

**Comment by ebroder** [comment]
This issue has been linked to an error in Bugsnag
[**TypeError** in **/hunts/m8meaNgtfrKfkiapd/puzzles/WZ5Dqps6oGn6jJHo8**](https://app.bugsnag.com/death-and-mayhem/jolly-roger/errors/63c2216403b8220008c76b53?event_id=63c4a3e600ab64e9bf160000&i=gh&m=li)

**Comment by zarvox** [comment]
Question: is the desired behavior here that we show the guess (implying a need for the relevant data-fetching to include deleted fields) or that we just skip over the guess that references a deleted puzzle?  Is the desired behavior different for the GuessQueuePage and the NotificationCenter?

**Comment by ebroder** [comment]
This issue has been linked to an error in Bugsnag
[**TypeError** in **/hunts/X9oKgbGvSSTr4zCzH/guesses**](https://app.bugsnag.com/death-and-mayhem/jolly-roger/errors/63c9a49c1d400d0008f28b58?event_id=63c9a4f200ac5dce80f00000&i=gh&m=li)

**Comment by ebroder** [comment]
Hmm. I think that IMO the desired behavior is that we should skip over those guesses on both, with the possible exception that operators should see deleted guesses on GuessQueuePage (but not NotificationCenter, similar to how they're the only ones that see deleted puzzles on PuzzleListPage)

**Comment by zarvox** [comment]
Since we don't currently have a mechanism by which we soft-delete `Guess`es (and I doubt that having one would be particularly useful), I'm inclined to just handle the case where a `Guess` references a `Puzzle` id for a deleted or unknown puzzle by simply pretending the Guess object does not exist.

Arguably, we should also forbid transitioning `Guess` state for guesses on `Puzzle`s that are deleted, since we could wind up trying to run solved/unsolved hooks for a puzzle that doesn't exist, or miss the update (making the `Puzzle`'s denormed `answers` list inconsistent with the set of `Guess`es).
