### ISSUE TITLE
Guess queue search does not search by submitter

### ISSUE THREAD

**Issue by ebroder** [deathandmayhem/jolly-roger#1372]
There were a few times this weekend I wanted to search for all guesses I had submitted.

**Comment by zarvox** [comment]
Yeah. I recall the reason for not doing this being that we need to join against users display names, and not wanting to write that complicated code at the time.  We probably need to either make the all guesses publication join in display names, or just subscribe to both and make sure both have loaded client-side before rendering.

**Comment by ebroder** [comment]
We certainly have them already, since we show the submitter name in the queue table
