### ISSUE TITLE
Make breadcrumbs look like breadcrumbs

### ISSUE THREAD

**Issue by aldeka** [deathandmayhem/jolly-roger#195]
This may involve ripping out the bootstrap nav, since this application reeeeeaaally isn't using as a navbar for the most part.

**Comment by aldeka** [comment]
(oh hey, now I see they do have slashes in between. Would prefer >s but that's better than no separator at all)

**Comment by ebroder** [comment]
Because we're building bootstrap from less ourselves, I think it's pretty easy to override this if we want to with something like

```diff
diff --git a/imports/client/stylesheets/bootstrap.less b/imports/client/stylesheets/bootstrap.less
index 0960b4d..1d68504 100644
--- a/imports/client/stylesheets/bootstrap.less
+++ b/imports/client/stylesheets/bootstrap.less
@@ -1,3 +1,4 @@
 @import "../../../node_modules/bootstrap/less/bootstrap.less";
 
 @icon-font-path: "/fonts/";
+@breadcrumb-separator: ">";
```

**Comment by grantaelliott** [comment]
@aldeka It sounds like this issue is resolved, as you seem satisfied with the slashes. Or do you (or anyone else) have a strong preference for greater-than? It's easily changed, though my personal preference is to stick with the default that users have likely encountered frequently elsewhere.

**Comment by grantaelliott** [comment]
Closing this long-idle issue, as it seems to be resolved. If anyone has an opinion about this, feel free to reopen.
