### ISSUE TITLE
Bugsnag failing to send client-side events

### ISSUE THREAD

**Issue by jpd236** [deathandmayhem/jolly-roger#2131]
Seeing JS errors in the log after actual errors:

```
[bugsnag] Event failed to send… Error: Request failed with status 0
    at ey.onreadystatechange (76d9292fb3a47a03a0eae3d3561909c11809ddfd.js?meteor_js_resource=true:10:31287)
```

I know the API key is set properly because server-side errors are reporting fine from the same instance.

**Comment by ebroder** [comment]
Do you have an ad blocker installed? IIRC many of them block Bugsnag by default

**Comment by jpd236** [comment]
Yep, that'll do it. I was expecting the library to proxy the reporting through the server to avoid that sort of thing, but that doesn't look to be a typical mode of operation.
