### ISSUE TITLE
Consider moving navigation list on hunt page

### ISSUE THREAD

**Issue by grantaelliott** [deathandmayhem/jolly-roger#220]
The list of three navigation links on the hunt landing page is oddly located alongside the puzzle filter controls, despite not being related to filtering (or in some cases, puzzles).  It would make sense to promote these in a way that emphasizes their role as navigation, perhaps as a horizontal list at the top of page.

The "Add a puzzle" button for operators is also located here, but both makes sense in the context and would fit nicely in the layout if the list of links is moved elsewhere.

**Comment by zarvox** [comment]
Fixed by #224
