### ISSUE TITLE
Improve "related puzzles" pane

### ISSUE THREAD

**Issue by ebroder** [deathandmayhem/jolly-roger#234]
The related puzzles pane on the puzzle page doesn't seem to have proven very useful. I think we intended for it to surface potential answer constraints on individual puzzles, but people don't really do that. At most, it's maybe useful for metas.

We should likely hide or remove the related puzzles pane, although maybe we should leave it around on puzzles tagged with `is:meta`. We could either replace it with more chat, or possibly display a list of useful solving tools or similar.

**Comment by grantaelliott** [comment]
I've found the related puzzles pane useful in the past and would prefer not to remove it entirely, though I agree that extended chat history would be more useful on most puzzles. I would support simply collapsing the pane by default on puzzles that are tagged neither is:meta nor meta-for:*

**Comment by grantaelliott** [comment]
Tentatively closed, by #271. Worth revisiting if we come up with new information worth presenting in some cases.
