### ISSUE TITLE
Guess notification should link to JR puzzle page

### ISSUE THREAD

**Issue by ebroder** [deathandmayhem/jolly-roger#235]
When a new guess comes in, operators frequently want to stop by the puzzle page to see where the guess came from, do some sanity checking, etc. But the notification links directly to the guess submission page on the Hunt website. We should link to the Jolly Roger puzzle page instead, maybe with an additional link (using the font awesome puzzle piece?) to the actual submission page.

**Comment by grantaelliott** [comment]
It looks to me like the Jolly Roger page is the more important one, but I'm not a frequent operator. It might be smart (and easy) just to replace the existing inline link with a link to the JR page.

Regarding the puzzle-piece icon, we currently use that for external link to the puzzle on the puzzle list page (but then we use the external link icon for the same thing on the JR puzzle page). We should be careful about introducing contradictory uses. (Looking at it now, I think I'd support using the external link icon for external puzzle links everywhere.)

**Comment by grantaelliott** [comment]
Closed by #275
