### ISSUE TITLE
Update Slack integration to use current APIs

### ISSUE THREAD

**Issue by ebroder** [deathandmayhem/jolly-roger#240]
Right now the Slack integration relies on using a ["legacy" token](https://api.slack.com/custom-integrations/legacy-tokens). However, they're marked as deprecated. I got an email today that they were planning to start sweeping unused legacy tokens (which is especially problematic for us, since our tokens go unused for 362 days of the year or so).

If we want to continue supporting invitations (which require a token with the `admin` scope), then we probably need to use Slack Apps. There's no way to have an open-source project where different installations use the same app, so we'd need to instruct each user to create a new application for their Jolly Roger install, and then get an OAuth token off of that. The [Slack Invite Automation](https://github.com/outsideris/slack-invite-automation#issue-token) app has fairly good instructions for how that flow works; we could just copy it.

**Comment by zarvox** [comment]
This ticket is obsolete -- Slack has since restricted `admin`-scoped tokens to where they can only be done via Slack Enterprise Grid, which is outside of our price range and would require new integration work.  Instead, we removed Slack support in #324.
