### ISSUE TITLE
Update guess queue page to match notifications

### ISSUE THREAD

**Issue by grantaelliott** [deathandmayhem/jolly-roger#293]
Guess notifications now have separate links to the hunt and JR puzzle pages (see #235). The guess queue page should be updated to match.

**Comment by zarvox** [comment]
This appears to have been resolved some time ago via [a "discussion" link](https://github.com/deathandmayhem/jolly-roger/blob/789d4b4026452ddca323dacc4967ebd37bbc62a3/imports/client/components/GuessQueuePage.tsx#L113) for each guess on the guess queue page.

**Comment by grantaelliott** [comment]
You're right; I just didn't see it. Thanks for closing this.

The guess queue page could probably use some style clean-up at some point (consistent icons and the like) to make features like this more evident, but that's a very low priority.
