### ISSUE TITLE
Fix answer rendering

### ISSUE THREAD

**Issue by grantaelliott** [deathandmayhem/jolly-roger#294]
Answers are currently rendering very badly on puzzle pages in some browsers. A large amount of blank space appears after the answer and spaces are very wide (see Safari screenshot below). This does not affect emoji answers.

![screenshot](https://user-images.githubusercontent.com/2136874/72772660-817f5c80-3bd2-11ea-8853-73b61f9ccba4.png)

This appears to be caused by the addition of the Apple Color Emoji font family.

**Comment by ebroder** [comment]
Dup of #291
