### ISSUE TITLE
Figure out a workaround for uploading images

### ISSUE THREAD

**Issue by ebroder** [deathandmayhem/jolly-roger#298]
Google Sheets' upload form has an `X-Frame-Options: sameorigin` header, which prevents it from working when it's iframe'd by Jolly Roger. We should figure out some way to make it possible to upload images.

(One potential option: it looks like Google Apps Script has an `Spreadsheet.insertImage` API that we might be able to build around)

**Comment by grantaelliott** [comment]
In the meantime, should we make the Sheet link always visible? Currently, it's only shown in narrow view or on devices with course pointers (as an approximation of devices on which the web interface is likely poor).

**Comment by zarvox** [comment]
The original reason we didn't make the sheet link visible on desktop was to keep people from opening the sheet separately on desktop (and as a result, ignoring other people writing things in the chat).  That seems less likely to be a problem now -- most people have used Jolly Roger before, and I suspect folks are much less likely to be working on things and blindly ignoring chat/audio calls.

I think I'd be on board with keeping the sheet link visible at all times, though of course the hacky, already-available workaround is to simply shrink your window until it hits the narrow view width.

**Comment by ebroder** [comment]
I'll leave a note here for reference, although I have aspirations of working on this myself.

I believe that the way we use Apps Script is that we need to [create a new project](https://developers.google.com/apps-script/api/reference/rest/v1/projects/create) for each document that is "bound" to that document. Once you've done that, you can upload some (presumably preexisting) script to the project, and then [run](https://developers.google.com/apps-script/api/reference/rest/v1/scripts/run) the script. I believe that you need a bound project in order to access the "current sheet" programmatically (via `scripts.run`).

If we _do_ start uploading an App Script to each document that we create, we should think about how we're going to keep it up to date if we need to change the App Script code. It would also be a good opportunity to setup a trigger for #107 and #173

**Comment by ebroder** [comment]
Ugh unfortunately I've since learned that there's a [quota on creating Apps Script projects](https://developers.google.com/apps-script/guides/services/quotas) of 50 projects per day, which is definitely not enough, so I'm no longer sure what the right approach for this would be.

**Comment by ebroder** [comment]
Today I discovered [this StackOverflow answer](https://stackoverflow.com/a/48919960). I'm not entirely clear on what can be done with App Script web apps. There might be something here, but we may also end up stymied again by clickjacking protections on Google's side - we somehow need to get the user to navigate to the web app in order to authenticate, and then we somehow need to send a request. (Which sounds an awful lot like we're trying to intentionally XSRF ourselves)

Alternatively, we could potentially use `"executeAs": "USER_DEPLOYING"` - that would be sufficient from a permissions perspective since we have access to all documents but isn't great from a "don't be responsible for user-generated content" perspective. Maybe we just kick that can further down the road.
