### ISSUE TITLE
Proposal: Move Related Puzzles to modal

### ISSUE THREAD

**Issue by grantaelliott** [deathandmayhem/jolly-roger#336]
Particularly in light of the renewed importance of chat this year, I'd like to revisit the question of what to do with Related Puzzles. In the past, I've been a proponent of keeping it at least available as always visible, but I now think it would be better to move it to a modal, with a trigger in the Metadata pane (as with Viewers and Guesses). The current behavior is to collapse the Related Puzzles automatically except on puzzles with meta tags.

Pros:
* Prioritize chat
* More space for related puzzles in the modal (less wrapping of titles and, in extreme cases, cutoff of answers)
* Unify the behavior of Guesses, Viewers, and Related Puzzles as parts of the metadata
* Eliminate the short-height layouts
* Simplify the interface visually
* Remove ability to hide chat on low-height mobile layouts

Cons:
* Lose at-a-glance pattern spotting (now one click away)
  * In non-metas, spotting patterns in sibling answers is already lost for most users as Related Puzzles is automatically collapsed.
  * In metas, child answers are usually copied into the sheet quickly.
  * Losing at-a-glance pattern spotting between sibling metas is notable, though it doesn't come up often.
* Lose at-a-glance awareness of a new child answer
  * The notification system serves the same purpose and is much more obvious.

I'd be interested in hearing opinions on this, particularly from those who frequently work on metas.

(The impetus for rethinking this was actually a long-standing but very minor issue for some mobile users that is now unavoidable even within the current generation iPhone lineup. On the puzzle page in narrow view, the transition from adjustable panes to tabs may occur when the browser chrome is hidden, creating a jarring user experience. Currently this affects the iPhone 12 and 12 Pro.)

**Comment by zarvox** [comment]
I'm largely in favor of this.  I'd not be sad if we also reworked the puzzle metadata section to use the space more efficiently.  I'd be pretty comfortable with showing this information on hover over the appropriate related puzzles section (with click making the visibility sticky, so as to support devices without hover), which could help reduce the cost of at-a-glance patter spotting where desired while retaining support for non-cursor interfaces.

The audio call support (and presence) that I'm working on will likely take up some amount of space in the chat pane, which is an additional motivation to get more space for the chat pane by default.

**Comment by grantaelliott** [comment]
I like both of these ideas (audio interface in the chat pane and using hover). Unfortunately, related puzzles frequently is many lines tall and requires scrolling, which may make such an interface unwieldy. Sticky visibility could address that.

Setting that aside, I could see related puzzles, viewers, and overflowing tags (see #288) all using a dropdown on hover. Guesses could as well, with a separate "submit a guess" button that opens a model.

**Comment by zarvox** [comment]
It is my intent to remove the viewers functionality from the metadata pane as we add it to the chat pane, so that's one less thing.

I'd leave the "submit a guess" button in the metadata section proper -- I feel like the information scent is important.

**Comment by grantaelliott** [comment]
That's a good idea. Viewers makes more sense in the dedicated chat pane.

How do you feel about separating "Submit a guess" from "View guess history", since the latter could use the proposed hover dropdown display?

**Comment by zarvox** [comment]
> How do you feel about separating "Submit a guess" from "View guess history", since the latter could use the proposed hover dropdown display?

They're the same button/modal today.  I guess the idea is that if they were separate, one could be active on hover to make it zero clicks (hover only) to see the guess history?  I'm not sure the distinction is super useful unless there's a different presentation you'd like to see for viewing the guess history from submitting a guess.  I still want the guess history shown in the guess-submission pane so people have a chance of not submitting duplicate guesses to the queue if they're paying attention.

**Comment by zarvox** [comment]
I just had an idea here -- what if we made related puzzles show up on hover/click on the individual `group:*` Tags?  Seems like the perfect piece of already-shared context with information scent to hide the thing we don't want to visualize all the time, and takes up no additional space in the puzzle metadata pane (since we're already showing the Tags).

I could see us doing this specifically for just `group:*` Tags, or for all Tags for consistency.

**Comment by grantaelliott** [comment]
I like that. The popover could also appear on tags in the main puzzle list.

There are some special cases to consider. For instance, meta-for should bring up the corresponding group (which the puzzle may or may not itself be a part of). Of course, is:meta would still bring up other metas, so nothing’s been lost.

I’m growing a little skeptical of hover for this, especially since scrolling is a possibility, and a hover / click-to-pin interface is potentially non-obvious.

The biggest downside I see is that it’s hard to at-a-glance spot patterns in two different sets (you’d have to intentionally check each), but that’s hard now as well, since the sets that matter aren’t necessarily near each other in the list and related puzzles frequently has little space.

I’ve been toying with moving the list of tags into a modal/popover as well. Listing them all on the puzzle page takes up space (sometimes way too much on mobile) and isn’t that helpful. While there’s an argument for seeing them at a glance, I think it’s basically equivalent to seeing related puzzles and putting them, for example, one click away isn’t too big a barrier for the player actually seeking that information. Some form of tag-explorer modal could make related puzzles a lot easier to assimilate than what we have now, while freeing up space for more pressing concerns (voice chat controls and extra puzzle document space), but I’m not sure what a good interface for that would be.
