### ISSUE TITLE
Inconsistent behavior with excess answers

### ISSUE THREAD

**Issue by grantaelliott** [deathandmayhem/jolly-roger#338]
On the puzzle list, a puzzle with more answers than expected renders in the style of an unsolved puzzle, but is shown and hidden as a solved puzzle. This is due to an inconsistent definition of "solved"

Styling is determined by equality of answer count:
https://github.com/deathandmayhem/jolly-roger/blob/f40316407639ef2b5f942ed9f98411ab229f92bf/imports/client/components/Puzzle.tsx#L84

Inclusion when Show Solved is inactive is determined by sufficiency of answer count:
https://github.com/deathandmayhem/jolly-roger/blob/f40316407639ef2b5f942ed9f98411ab229f92bf/imports/client/components/PuzzleListPage.tsx#L146

I can see an argument for treating a puzzle as unsolved if it has more answers than expected (after all, there's something about it that we don't understand), but this feels like a special case that warrants different presentation. In any case, these behaviors should be consistent.

**Comment by zarvox** [comment]
I think it makes sense to make the check in Puzzle.tsx be >= rather than ===.

In any case, I think the only way we get into this situation is:
* operator confirms more correct answers than apply to the puzzle
* after confirming too many answers, operator edits the expected answer count down below the current number of correct answers

both of which seem unlikely to be a substantive issue in practice.

**Comment by grantaelliott** [comment]
Yeah, it's a vanishingly rare occurrence. That said, it might actually matter if a puzzle truly surprises us with extra answers (which is almost always the case at least initially when multiple answers are in play).

For that reason, I suggest we introduce a dark-green "oversolved" class and change the puzzle list to show oversolved puzzles when hiding solved. That way, until the operators have confidence in the expected number of answers, we can continue to promote the puzzle as pending, without misrepresenting its solved status (Truly supporting such cases would include having a means of setting the expected answer count to unknown).

**Comment by grantaelliott** [comment]
For now, I'm submitting a PR consistently treating oversolved puzzles as solved (it also comes up in a couple of other places, like sorting, or selecting guess button text), per @zarvox above. We can always revisit if we're concerned with surfacing oversolved puzzles.
