### ISSUE TITLE
Modal dialogs trigger excessive time in layout on first render

### ISSUE THREAD

**Issue by zarvox** [deathandmayhem/jolly-roger#342]
Navigate to the puzzle list page of any hunt, and click the Add Puzzle button (or if you're not an operator, navigate to any puzzle page and click the "Submit a guess" or "See {num} guesses" button).  Time how long it takes for the modal to appear.  It'll be on the order of seconds.  That's frustratingly slow.

A profile reveals that this time is spent in layout, reflowing from the #document root.  Not sure if this is an issue in react-bootstrap or what.

![Screenshot_20201127_201532](https://user-images.githubusercontent.com/307325/100493625-b232fb00-30ed-11eb-94ea-a2a768349b5e.png)

**Comment by grantaelliott** [comment]
I'm unable to reproduce this in Chrome or Safari. Both of the mentioned modals open immediately in every configuration I've tried. Any idea what might be different about your case?

**Comment by zarvox** [comment]
Hmmm.  According to chrome://settings/help, this is Chrome Version 87.0.4280.66 (Official Build) (64-bit), obtained via Google's official repositories, running atop Fedora 33.  But for me this happens consistently, the first time a modal is shown (but then it's snappy again after the first time the page has shown a modal).

**Comment by zarvox** [comment]
I'm able to reproduce this on ChromeOS as well, so I think this probably affects all Linux builds.

**Comment by zarvox** [comment]
I suspect this may have been somehow triggered by the previous fonts situation, because I'm no longer able to reproduce this from Linux.  I'll test ChromeOS and if things are peaceful there too, I'll close the bug.

**Comment by zarvox** [comment]
Confirmed that I'm unable to repro this on Linux or ChromeOS.  Closing under the presumption that it was triggered by needing to determine font metrics on Linux for a font that had not already been shaped.
