### ISSUE TITLE
Puzzles with no group have different behavior in puzzle list

### ISSUE THREAD

**Issue by grantaelliott** [deathandmayhem/jolly-roger#347]
In the PuzzleListView, the implicit group of puzzles with no group currently renders slightly differently:

- The section heading ("Puzzles in no group") has no preceding down caret, so it appears to be spaced differently (and it has a trailing colon)
- The section cannot be collapsed

It's a very minor concern, but I think this group should be collapsible, like the others. Was this a deliberate decision?

**Comment by zarvox** [comment]
I have no objections to making group-less puzzles collapsible.  I think this was mostly an effort to make sure puzzles didn't get lost into the aether in the group view if they didn't have a group tag.  Happy for this to become consistent!
