### ISSUE TITLE
Related puzzle popover doesn't close when clicking into document on mobile

### ISSUE THREAD

**Issue by grantaelliott** [deathandmayhem/jolly-roger#377]
This issue affects only browsers without hover (notably, typical mobile usage). When hover is not available, clicking outside the related puzzles popover is supposed to close it, but this does not occur when clicking into the document iframe. (The document in the iframe still responds appropriately.)

**Comment by zarvox** [comment]
Would it make sense for the popover to add a `blur` event listener on the top-level window in `componentDidMount` (and remove it in `componentWillUnmount`) to dismiss this dialog?  I think that event fires when focus goes into the iframe (and also when we focus another window, but that seems fine)?
