### ISSUE TITLE
Chat text moves without new messages appearing

### ISSUE THREAD

**Issue by catoverdrive** [deathandmayhem/jolly-roger#427]
I noticed a few times this past weekend that the text in the chat window seemed to move even though new messages weren't being sent. This is only mildly annoying, but definitely distracting if you're trying to monitor the chat while puzzling. I think (but haven't verified) this might happen as new viewers open the puzzle or join the audio call causing the box above the chat to resize. Of course, it could also be my eyes playing tricks on me.

(Browser: Google Chrome Version 87.0.4280.141)

**Comment by zarvox** [comment]
Ohhhhh it's probably the length of the audiocall + viewers pane growing (or shrinking) by a row.  Yeah, that sounds like something we could probably be smarter about handling -- forcing scroll to the bottom when the height allocated to the chat history pane changes due to viewer/caller join/part.
