### ISSUE TITLE
Use Google Drive folders for permission management instead of documents

### ISSUE THREAD

**Issue by ebroder** [deathandmayhem/jolly-roger#497]
We've had problems in the past with our strategy of granting team members access to documents (to avoid them being anonymous animals), especially near the beginning of hunt, because everyone swarms the docs all at the same time, causing us to hit rate limits.

One potential way to avoid this: when you create a hunt, also create a folder in Google Drive. When someone joins the hunt, give them access to the Google Drive folder. When creating new docs for a puzzle, create them in the folder. That should reduce permissions from an `O(hunters * puzzles)` problem to just `O(hunters)`.

**Comment by zarvox** [comment]
I'm presuming that approach would still reveal identities in the docs iframe?

**Comment by ebroder** [comment]
I'm not actually sure - we should test it - but I don't see why it wouldn't? AIUI, access to a folder in Drive gives you access to the doc as if it were granted directly
