### ISSUE TITLE
Come up with a more explicit story around log retention

### ISSUE THREAD

**Issue by zarvox** [deathandmayhem/jolly-roger#516]
Today, we don't really exercise any controls around how much disk space various logs can take up.  By default, Docker has unlimited log retention, and our various containers do the container-appropriate thing of logging to `stdout` and `stderr`.

But on a long-lived server, it's possible that the logs will grow without bound, potentially making the machine fail to download new container images or otherwise make useful progress.  We've probably largely avoided hitting this through some combination of logging relatively sparsely and (probably) watchtower deleting the old container, causing (effectively) log truncation when container images are updated, and those images have updated frequently enough that no log has grown excessively.

It would be nice if we were actually enforcing that in some way, by limiting the amount of space we allow logs to take before splitting/rotating them.

This isn't particularly urgent; we've been running this way for years without really noticing, but if there were something that led to us logging substantially more, we could potentially find ourselves hitting this issue.

**Comment by ebroder** [comment]
It looks like the way to do this is probably to set `max-size` on the [logging driver config](https://docs.docker.com/config/containers/logging/json-file/#options)
