### ISSUE TITLE
Respaced related puzzles include non-alphanumerics

### ISSUE THREAD

**Issue by grantaelliott** [deathandmayhem/jolly-roger#602]
If punctuation is included in the canonical answer, it's rendered in the respaced presentation as well. (That is "respace" only eliminates whitespace characters.)

Fortunately, the standard presentation is also offered, so edge case failures cause minimal damage. Nonetheless, I'm hesitant to simply remove all non-alphanumerics in the respaced presentation because sometimes those are real content (e.g. emoji). Once a fix for #600 lands, my inclination is to say that the operator's job is to ensure that only contentful characters and whitespace make up canonical answers. That still leaves apostrophes and similarly meaningful characters.

My suggested fix is to curate a list of characters to be removed in the respaced presentation. Tentatively, this includes `.?!,-_'"()`.

**Comment by ebroder** [comment]
I worry that curating a list of characters is a good way to leave us scrambling the next time there's an emoticon round.

**Comment by grantaelliott** [comment]
That's true, but to some extent, the solution to that is "don't use the respace presentation in the round where it's not applicable" just like you wouldn't use it in a round with clearly semantic answers. I'm not calling for removing the canonical presentation (which is the default).

**Comment by ebroder** [comment]
Ah, I see. I misread this as answer canonicalization, but I'm in favor of this.
