### ISSUE TITLE
Audio feed from Safari can be muffled by broad noise

### ISSUE THREAD

**Issue by grantaelliott** [deathandmayhem/jolly-roger#603]
Users on Safari are occasionally rendered unintelligible. This is resolved by leaving the call and rejoining.

This seems to happen only after the JR page loses focus, but my understanding of the necessary or sufficient conditions is inadequate.

**Comment by ebroder** [comment]
I'm seeing some indication around the internet that `createMediaStreamSource` in Safari may be misbehaving, and we should use `stream.clone()` instead. I'm not entirely sure that will work for us (I think there are cases where we need an `AudioNode` and not a `MediaStream`?) but we should experiment.

**Comment by grantaelliott** [comment]
No longer able to reproduce this. Whether by #967 or by a change in Safari, I believe this is fixed.
