### ISSUE TITLE
Merge profiles collection into users

### ISSUE THREAD

**Issue by ebroder** [deathandmayhem/jolly-roger#628]
We previously avoided storing publicly-visible data about users on Meteor's users collection. There were a few specific concerns:

* We might accidentally expose other data that should remain private (especially things like `users.services`)
* The `profile` field on users is default writeable from the client, meaning that we couldn't enforce schema

However, there are significant drawbacks to having a separate profiles collection. There are several queries we'd want to write that require joining against users (e.g. "find the profile for all users that are in hunt X"), and we have to contemplate the possibility that the user has no profile (c.f. #407). These drawbacks become more significant as (e.g.) we consider allowing anyone to create a hunt and thus want to be more respecting of privacy for non-overlapping users.

I'm not sure there's a good technical mitigation for the first concern, though certainly care and inspection where we publish user data will be important. The second is much easier to handle - the Meteor documentation specifically [recommends](https://docs.meteor.com/api/accounts.html#:~:text=To%20forbid%20users%20from%20making%20any%20modifications%20to%20their%20user%20document%3A) creating a new `deny` rule to overrule the default `allow` rule that allows writing to the `profile` field.

Given that, we should merge profiles into users. I propose specifically merging it into the `profile` field, rather than creating something new. I would specifically propose _not_ merging `hunts` and `roles` onto the `profile` field. My mental model for the new `profile` field is that we may not be willing to publish the profile to all users, but if we're willing to publish a profile to a given user, that user should receive the entirety of the field. For `hunts` and `roles`, I think we would want to filter them further (e.g. two users can see which hunts they overlap on, but not the other's hunts that they weren't involved with).

I think there are three main things to be careful with when this is implemented:

* We must make sure to add the `deny` rule to block edits to `profile`
* Our current logic publishes all profiles to any logged-in user; we'll likely need to continue to do so, but need to be careful about which fields we publish (and how that interacts with our normal strategy of letting the client specify `fields` and other query options
* When migrating the data over, we should make sure to explicitly nuke anything that has been manually set on the existing `users.profile` field, since we've historically run with the default allow rule.

**Comment by zarvox** [comment]
I share your intuition about not merging hunts and roles onto the profile field, and being willing to share either the whole profile object or none of it.

Is publishing or querying for a subset of an array field (ala `hunts`) possible?  That seems like something where you'd have to synthesize the intersection dynamically at runtime, which could be kinda complicated.

Your 3 main things sound pretty spot-on, but I'll add one more: we should think about what to do when a user has no profile, or fields of their profile are not set.  It's possible (when users miss their initial invitation email and then do a password reset to first login) to sidestep the flow we used to set up Profile initially; so some users may be missing Profiles entirely and we should figure out how to handle that.  Previously, we accomplished this by querying primarily on the Profiles table for account IDs that we knew shared this hunt and not really noticing if the result set was smaller than the pool of IDs; now we will need to be more explicit about handling missing profiles.

**Comment by ebroder** [comment]
Hmm. Projection syntax is pretty limited. Maybe if we made `hunts` a `Record<string, boolean>` (i.e. `{"huntId": true}`), then we might be able to project something like `{ hunts: 0, "hunts.huntId1": 1, "hunts.huntId2": 1 }` and use that to slice a hunts subdoc, but I'd need to experiment some with whether that works or not (but the new `roles` field should give us an easy way to play with it)

**Comment by ebroder** [comment]
Doesn't quite work:

```
meteor:PRIMARY> db.users.find({_id: 'pYTYfhRDNcCMmqaAd'})[0].roles
{
	"__GLOBAL__" : [
		"admin"
	],
	"cSB2bWf3BToQ9NBju" : [
		"operator"
	],
	"GS3hfkZKN3zbGK4Hg" : [
		"operator"
	]
}

meteor:PRIMARY> db.users.find({_id: 'pYTYfhRDNcCMmqaAd'}, { roles: 0, 'roles.__GLOBAL__': 1 })[0].roles
Error: Error: error: {
	"operationTime" : Timestamp(1642750612, 1),
	"ok" : 0,
	"errmsg" : "Path collision at roles.__GLOBAL__ remaining portion __GLOBAL__",
	"code" : 31249,
	"codeName" : "Location31249",
	"$clusterTime" : {
		"clusterTime" : Timestamp(1642750612, 1),
		"signature" : {
			"hash" : BinData(0,"AAAAAAAAAAAAAAAAAAAAAAAAAAA="),
			"keyId" : NumberLong(0)
		}
	}
} :
@(shell):1:1
```

but if you don't try to mix-and-match it does work:

```
meteor:PRIMARY> db.users.find({_id: 'pYTYfhRDNcCMmqaAd'}, { 'roles.__GLOBAL__': 1 })[0].roles
{ "__GLOBAL__" : [ "admin" ] }
```

But the downside of that approach is that it means that your projection is an allowlist - i.e. you have to explicitly enumerate all fields (besides `_id`) that you want to return:

```
meteor:PRIMARY> Object.keys(db.users.find({_id: 'pYTYfhRDNcCMmqaAd'})[0])
[
	"_id",
	"createdAt",
	"services",
	"emails",
	"hunts",
	"profile",
	"roles",
	"lastLogin"
]
meteor:PRIMARY> Object.keys(db.users.find({_id: 'pYTYfhRDNcCMmqaAd'}, { 'roles.__GLOBAL__': 1 })[0])
[ "_id", "roles" ]
```

Still, might be workable...

**Comment by ebroder** [comment]
Oh wow you can also do it with an array using `$elemMatch` - I didn't realize you could use that in a projection:

```
meteor:PRIMARY> db.users.find({_id: 'pYTYfhRDNcCMmqaAd'})[0].hunts
[ "cSB2bWf3BToQ9NBju", "GS3hfkZKN3zbGK4Hg" ]
meteor:PRIMARY> db.users.find({_id: 'pYTYfhRDNcCMmqaAd'}, { hunts: 1 })
{ "_id" : "pYTYfhRDNcCMmqaAd", "hunts" : [ "cSB2bWf3BToQ9NBju", "GS3hfkZKN3zbGK4Hg" ] }
meteor:PRIMARY> db.users.find({_id: 'pYTYfhRDNcCMmqaAd'}, { hunts: { $elemMatch: { $eq: 'GS3hfkZKN3zbGK4Hg' } } })
{ "_id" : "pYTYfhRDNcCMmqaAd", "hunts" : [ "GS3hfkZKN3zbGK4Hg" ] }
```

But again, the projection is an allowlist so we'd have to explicitly enumerate fields.

**Comment by zarvox** [comment]
That doesn't seem so bad as long as minimongo also properly supports $elemMatch?  We almost certainly want to be enumerating fields anyway so we don't accidentally publish the sensitive resume tokens from `services`.

I guess the shape of a serverside-reactive hunt-intersection user query would be something like:

* query Meteor.users for _id: this.userId
* observe that object; on added/changed grab all the keys off `hunts` and see which we're already watching
* for each hunt added:
  * do a query for users with that hunt, with the fields we're intending to publish (maybe do some RefcountedObserverMap shenanigans)
* for each hunt removed:
  * tear down the hunt-specific watcher

And then theoretically, each of the live queries on a single, specific hunt should be deduplicated by Meteor, which should cap out the number of live queries at a pretty manageable number?

**Comment by ebroder** [comment]
I think, for the record, most of this discussion is more relevant to #629 than it is to #628 - my main call out on this issue was around whether or not to move `hunts` and `roles` under `users.profile`, and seems like we're in agreement that we should not. (Mostly calling this out to get the issue link)

One option instead of having a complex hunt intersection query is to require that `useSubscribeDisplayNames` and similar be scoped to an individual hunt. The only place where we _aren't_ scoped to a hunt is the NotificationCenter, but we already have fancy subscriptions for `chatNotifications` and `pendingGuesses`. If we (a) added a fancy subscription for `pendingAnnouncements` (b) published `displayName` with all three of those, we might need to do any server-side intersection shenanigans at all.
