### ISSUE TITLE
Puzzle group sort issues

### ISSUE THREAD

**Issue by ebroder** [deathandmayhem/jolly-roger#697]
Two areas where we can probably improve on sorting:
- Currently, a group without a meta sorts below a group where all puzzles have been solved. We should put groups where all puzzles have been solved at the lowest priority.
- Currently, a group with multiple metas sorts to the bottom if one of the metas has been solved. It should sort to the top so long as _any_ meta is unsolved.

**Comment by zarvox** [comment]
> Currently, a group without a meta sorts below a group where all puzzles have been solved. We should put groups where all puzzles have been solved at the lowest priority.

The way this usually plays out in practice is that there often *will* be a meta, and maybe we don't want to forget about those groups of puzzles by throwing them to the end of the list.  But maybe we resolve this on the operator end by creating the stub meta entry if we need a place for people to ideate on the still-locked meta, and link it to the actual puzzle upon unlock.  I think it'd be reasonable to split out what is currently (0) https://github.com/deathandmayhem/jolly-roger/blob/2e4a7d17f0b71846d3dd2764de4bfa3b70210fdc/imports/client/components/puzzle-sort-and-group.ts#L82 into "(0) groups with no metas yet and at least one unsolved puzzle" and "(1.5) groups with no metas yet and all puzzles solved".

> Currently, a group with multiple metas sorts to the bottom if one of the metas has been solved. It should sort to the top so long as any meta is unsolved.

It currently sorts upwards but remains below groups where the meta-for: that specific group is unsolved.  That is, I believe that if we're talking about different `meta-for:*` values on the different metas, this is already the logic we apply (the unsolved `group:*` value bubbles up, and the solved `group:*` value bubbles way down).  I can imagine this not being the case if we have the same `meta-for:*` values for different puzzles, but it was not clear to me we intended to support that case.  For clarity, are you talking specifically about a case where multiple unique puzzles are each tagged `meta-for:foo` for the same `group:foo`?

**Comment by ebroder** [comment]
> For clarity, are you talking specifically about a case where multiple unique puzzles are each tagged `meta-for:foo` for the same `group:foo`?

Yes - you see this in the fixture data with Games Island. In the fixtures, The Desert has been solved but The Robber has not. I'm not sure intuitively how I would model the structure of that round other than two metas with the same `meta-for:*`. (In development, I believe we called them the "antemeta" and "supermeta")
